CREATE DATABASE cadastro;

 \c cadastro;

 CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
 );

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    conteudo TEXT NOT NULL
);

INSERT INTO users (name, email) VALUES
('Bernardo Marques', 'bernardo.marques@gmail.com'),
('Ana Julia', 'ana.ju@gmail.com'),
('Giovanna', 'gi.caron@gmail.com'),
('Amanda', 'amanda.mechi@gmail.com'),
('Julia', 'julia.neves@gmail.com'),
('Kevin', 'kevin.nino@gmail.com'),
('Thiago', 'thiago.dev@gmail.com'),
('Marcelo', 'marcelo.code@gmail.com'),
('Eduardo', 'eduardo.tech@gmail.com'),
('Felipe', 'felipe.prog@gmail.com'),
('Lucas', 'lucas.silva@gmail.com'),
('Mariana', 'mariana.santos@gmail.com'),
('Carlos', 'carlos.almeida@gmail.com'),
('Fernanda', 'fernanda.rocha@gmail.com'),
('Bruno', 'bruno.martins@gmail.com'),
('Camila', 'camila.oliveira@gmail.com'),
('Rafael', 'rafael.souza@gmail.com'),
('Larissa', 'larissa.costa@gmail.com'),
('Gabriel', 'gabriel.ferreira@gmail.com'),
('Isabela', 'isabela.pereira@gmail.com'),
('João', 'joao.vieira@gmail.com'),
('Beatriz', 'beatriz.melo@gmail.com'),
('Pedro', 'pedro.barbosa@gmail.com'),
('Sofia', 'sofia.ramos@gmail.com'),
('André', 'andre.lima@gmail.com'),
('Luana', 'luana.carvalho@gmail.com'),
('Rodrigo', 'rodrigo.teixeira@gmail.com'),
('Patrícia', 'patricia.moura@gmail.com'),
('Vinícius', 'vinicius.gomes@gmail.com'),
('Aline', 'aline.silva@gmail.com'),
('Matheus', 'matheus.santos@gmail.com'),
('Vanessa', 'vanessa.rodrigues@gmail.com'),
('Diego', 'diego.monteiro@gmail.com'),
('Renata', 'renata.alves@gmail.com'),
('Gustavo', 'gustavo.machado@gmail.com'),
('Carolina', 'carolina.castro@gmail.com'),
('Henrique', 'henrique.dias@gmail.com'),
('Juliana', 'juliana.martins@gmail.com'),
('Leandro', 'leandro.souza@gmail.com'),
('Tatiane', 'tatiane.mendes@gmail.com'),
('Ricardo', 'ricardo.oliveira@gmail.com'),
('Paula', 'paula.freitas@gmail.com'),
('Fábio', 'fabio.silva@gmail.com'),
('Natália', 'natalia.santos@gmail.com'),
('Alexandre', 'alexandre.costa@gmail.com'),
('Débora', 'debora.rocha@gmail.com'),
('Igor', 'igor.martins@gmail.com'),
('Simone', 'simone.oliveira@gmail.com'),
('Cláudio', 'claudio.souza@gmail.com'),
('Michele', 'michele.pereira@gmail.com');

INSERT INTO posts (name, conteudo) VALUES
('Bernardo', 'post de luta'),
('Ana ju', 'post de lira'),
('Gi', 'post de receita'),
('Amanda', 'post de gato'),
('Julia', 'post de pintura'),
('Kevin', 'post de festa'),
('Thiago', 'Post sobre programação orientada a objetos'),
('Marcelo', 'Post sobre banco de dados relacional'),
('Eduardo', 'Post sobre algoritmos e estruturas de dados'),
('Felipe', 'Post sobre desenvolvimento web com JavaScript'),
('Lucas', 'Post sobre esportes'),
('Mariana', 'Post sobre viagens'),
('Carlos', 'Post sobre música'),
('Fernanda', 'Post sobre culinária'),
('Bruno', 'Post sobre fotografia'),
('Camila', 'Post sobre moda'),
('Rafael', 'Post sobre tecnologia'),
('Larissa', 'Post sobre filmes'),
('Gabriel', 'Post sobre séries'),
('Isabela', 'Post sobre literatura'),
('João', 'Post sobre carros'),
('Beatriz', 'Post sobre decoração'),
('Pedro', 'Post sobre jardinagem'),
('Sofia', 'Post sobre yoga'),
('André', 'Post sobre meditação'),
('Luana', 'Post sobre maquiagem'),
('Rodrigo', 'Post sobre viagens de aventura'),
('Patrícia', 'Post sobre empreendedorismo'),
('Vinícius', 'Post sobre esportes radicais'),
('Aline', 'Post sobre saúde e bem-estar'),
('Matheus', 'Post sobre games'),
('Vanessa', 'Post sobre pets'),
('Diego', 'Post sobre astronomia'),
('Renata', 'Post sobre história'),
('Gustavo', 'Post sobre ciência'),
('Carolina', 'Post sobre arte'),
('Henrique', 'Post sobre política'),
('Juliana', 'Post sobre economia'),
('Leandro', 'Post sobre educação'),
('Tatiane', 'Post sobre psicologia'),
('Ricardo', 'Post sobre viagens internacionais'),
('Paula', 'Post sobre culinária vegana'),
('Fábio', 'Post sobre esportes aquáticos'),
('Natália', 'Post sobre fotografia de natureza'),
('Alexandre', 'Post sobre carros antigos'),
('Débora', 'Post sobre moda sustentável'),
('Igor', 'Post sobre inteligência artificial'),
('Simone', 'Post sobre marketing digital'),
('Cláudio', 'Post sobre design gráfico'),
('Michele', 'Post sobre organização pessoal');